feat(dictionaries): dictionaries API implementation
algolia/algoliasearch-client-kotlin pull request #247
Opened 2021-01-14 16:01 UTC by Aallam

Implement dictionaries API
- [ ] `saveDictionaryEntries`
- [ ] `replaceDictionaryEntries`
- [ ] `deleteDictionaryEntries`
- [ ] `clearDictionaryEntries`
- [ ] `searchDictionaryEntries`
- [ ] `setDictionarySettings`
- [ ] `getDictionarySettings`

2021-01-26 08:49 UTC, chloelbn requested changes

2021-01-26 11:22 UTC, VladislavFitz commented
I like the way you introduced the type safety for dictionaries methods. I started to do it in the same way in Swift, but when I found a type structure improvement that you may wish to apply to your implementation.

The questionable thing is the `DictionaryEntry<T>` structure. It resolves the type safety challenge, but semantically I think it is more consistent to make `DictionaryEntry` the descendant of a `Dictionary` and not the other way around.
The idea is that `Dictionary` is not just a string wrapper, but an interface providing a static `name` string and a generic  `DictionaryEntry` parameter.

```kotlin
interface Dictionary<Entry: DictionaryEntry> {
  // not sure how to define a static `name` a variable in the Kotlin interface
}
```

Therefore, each concrete dictionary is an implementation of this protocol:

```kotlin
class CompoundsDictionary: Dictionary<CompoundEntry>
```

As a result, the `Dictionary` parameter explicitly defines the type of its `Entry` and can be used directly in the methods as a `dictionary` parameter.
By doing so, I suppose, you can abolish the type-explicit methods such as `savePluralsEntries`, `deletePluralsEntries`, `searchPluralsEntries` by keeping their generic version.

I applied this approach at the last moment in the Swift implementation and it seems work well. You can check out the [Swift PR](https://github.com/algolia/algoliasearch-client-swift/pull/717/files) (you have to review it anyway 😁) to better understand my idea. 

What do you think?

2021-01-27 13:42 UTC, Aallam commented on src/commonMain/kotlin/com/algolia/search/endpoint/EndpointDictionary.kt
> +        clearExistingDictionaryEntries: Boolean = false,
Not sure if I am getting this right, should we the parameter from `saveDictionaryEntries` and set it always to false in the request?

2021-01-28 09:49 UTC, chloelbn commented on src/commonMain/kotlin/com/algolia/search/endpoint/EndpointDictionary.kt
> +        clearExistingDictionaryEntries: Boolean = false,
yes indeed! it'll be true only for replace

2021-01-28 10:09 UTC, Aallam commented on src/commonMain/kotlin/com/algolia/search/endpoint/EndpointDictionary.kt
> +        clearExistingDictionaryEntries: Boolean = false,
Fixed 🎉

2021-01-28 18:04 UTC, VladislavFitz approved these changes

2021-01-29 10:27 UTC, chloelbn approved these changes

2021-02-01 09:17 UTC, chloelbn approved these changes

2021-02-03 10:19 UTC, merged